[tool.poetry]
name = "sprawozdanie projektowe bazy danych 1"
version = "1.0.0"
description = ""
authors = ["Eryk Mika"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sphinx = "^7.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
